In [1]:
import pandas as pd
import numpy as np

## Load data

In [2]:
data_preprocessed = pd.read_csv(r"C:\Users\anees\Absenteeism_preprocessed.csv")

In [3]:

data_preprocessed.head()


Reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## Create Targets

In [4]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']> data_preprocessed["Absenteeism Time in Hours"].median() ,1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism']=targets

In [8]:
data_preprocessed.head()

Reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [9]:
targets.sum()

319

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)

In [12]:
data_with_targets is data_preprocessed

False

In [13]:
data_with_targets.head()

Reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Age  Body Mass Index  Education  Children  Pets  Month Value  \
0   33               30          0         2     1            7   
1   50               31          0         1     0            7   
2   38               31          0         0     0            7   
3   39               24          0         2     0            7   
4   33               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select inputs for regressiom

In [14]:
data_with_targets.shape

(700, 13)

In [15]:
data_with_targets.iloc[:,0:14]

Reason_1  reason_2  reason_3  reason_4        Date  \
0           0         0         0         1  2015-07-07   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-23   
697         1         0         0         0  2018-05-24   
698         0         0         0         1  2018-05-24   
699         0         0         0         1  2018-05-31   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Month Value  Excessive Absenteeism  
0              7                      1  
1              7                      0  
2              7                      0  
3              7                      1  
4              7                      0  
..           ...                    ...  
695            5                      1  
696            5                      0  
697            5                      1  
698            5                      0  
699            5                      0  

[700 rows x 13 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

## Standardize the data

In [17]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy               # ✅ Needed for get_params()
        self.with_mean = with_mean     # ✅ Needed for get_params()
        self.with_std = with_std       # ✅ Needed for get_params()
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), 
                                columns=self.columns, 
                                index=X.index)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [18]:
unscaled_inputs.columns.values

array(['Reason_1', 'reason_2', 'reason_3', 'reason_4', 'Date',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Excessive Absenteeism'],
      dtype=object)

In [19]:
#columns_to_scale = [ 'Transportation Expense', 'Distance to Work', 'Age',
       #'Daily Work Load Average', 'Body Mass Index','Children', 'Pets', 'Month Value', 'Day of the Week']
colums_to_omit =['Reason_1','reason_2','reason_3','reason_4','Education','Date']

In [20]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in colums_to_omit]

In [21]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value',
                      'Excessive Absenteeism'])

In [23]:
absenteeism_scaler

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value',
                      'Excessive Absenteeism'])

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Reason_1  reason_2  reason_3  reason_4        Date  \
0           0         0         0         1  2015-07-07   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-23   
697         1         0         0         0  2018-05-24   
698         0         0         0         1  2018-05-24   
699         0         0         0         1  2018-05-31   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  Month Value  Excessive Absenteeism  
0    0.268487     0.182726               1.092867  
1   -0.589690     0.182726              -0.915025  
2   -0.589690     0.182726              -0.915025  
3   -0.589690     0.182726               1.092867  
4    0.268487     0.182726              -0.915025  
..        ...          ...                    ...  
695 -0.589690    -0.388293               1.092867  
696  1.126663    -0.388293              -0.915025  
697 -0.589690    -0.388293               1.092867  
698 -0.589690    -0.388293              -0.915025  
699  0.268487    -0.388293              -0.915025  

[700 rows x 13 columns]

In [26]:
scaled_inputs.shape

(700, 13)

## Split the data

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
train_test_split(scaled_inputs,targets)

[     Reason_1  reason_2  reason_3  reason_4        Date  \
 394         0         0         0         1  2017-03-13   
 87          1         0         0         0  2015-11-16   
 333         0         0         0         1  2016-11-22   
 126         0         0         0         1  2016-01-15   
 605         0         0         0         1  2018-02-21   
 ..        ...       ...       ...       ...         ...   
 342         0         0         0         1  2016-12-05   
 242         0         0         0         1  2016-07-15   
 345         1         0         0         0  2016-12-15   
 88          0         0         0         1  2015-11-18   
 319         1         0         0         0  2016-11-08   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 394               -0.654143  0.248310         1.002633          0 -0.919030   
 87                 1.036026  0.562059        -0.408580          0 -0.019280   
 333               -0.654143  0.248310

In [29]:
x_train , x_test, y_train , y_test = train_test_split(scaled_inputs,targets,train_size = 0.82,random_state = 20)

In [30]:
print(x_train.shape,y_train.shape)

(574, 13) (574,)


In [31]:
print(x_test.shape,y_test.shape)

(126, 13) (126,)


## Logistic Regression with sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [33]:
x_train = x_train.drop('Date', axis=1)
x_test = x_test.drop('Date', axis=1)

reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

LogisticRegression()

In [35]:
reg.score(x_train,y_train)

1.0

## manually check the accuracy 

In [36]:
model_outputs = reg.predict(x_train)

In [37]:
model_outputs

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [38]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [39]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [40]:
np.sum((model_outputs == y_train))

574

In [41]:
model_outputs.shape[0]

574

In [42]:
560/448

1.25

In [43]:
448/560

0.8

## finding the intercept and coefficients

In [44]:
reg.intercept_

array([-0.48189595])

In [45]:
reg.coef_

array([[ 3.43770713e-01,  6.24074807e-04,  2.33853856e-01,
        -2.63597059e-01,  1.97549155e-01, -4.53446770e-02,
         7.05820658e-02, -1.18641950e-02,  1.39588381e-01,
        -7.05280795e-02,  6.86081139e-02,  4.65349458e+00]])

In [46]:
unscaled_inputs.columns.values

array(['Reason_1', 'reason_2', 'reason_3', 'reason_4', 'Date',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Excessive Absenteeism'],
      dtype=object)

In [47]:
unscaled_inputs=unscaled_inputs.drop('Date',axis=1)
feature_name = unscaled_inputs.columns.values


In [48]:
summary_table = pd.DataFrame (columns=['Feature name'],data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     0.343771
1                 reason_2     0.000624
2                 reason_3     0.233854
3                 reason_4    -0.263597
4   Transportation Expense     0.197549
5                      Age    -0.045345
6          Body Mass Index     0.070582
7                Education    -0.011864
8                 Children     0.139588
9                     Pets    -0.070528
10             Month Value     0.068608
11   Excessive Absenteeism     4.653495

In [49]:
summary_table.index = summary_table.index +1

In [50]:
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [51]:
summary_table

Feature name  Coefficient
0                Intercept    -0.481896
1                 Reason_1     0.343771
2                 reason_2     0.000624
3                 reason_3     0.233854
4                 reason_4    -0.263597
5   Transportation Expense     0.197549
6                      Age    -0.045345
7          Body Mass Index     0.070582
8                Education    -0.011864
9                 Children     0.139588
10                    Pets    -0.070528
11             Month Value     0.068608
12   Excessive Absenteeism     4.653495

## interpreting the coefficients

In [52]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficient)

In [53]:
summary_table

Feature name  Coefficient  Odds_Ratio
0                Intercept    -0.481896    0.617611
1                 Reason_1     0.343771    1.410255
2                 reason_2     0.000624    1.000624
3                 reason_3     0.233854    1.263460
4                 reason_4    -0.263597    0.768283
5   Transportation Expense     0.197549    1.218413
6                      Age    -0.045345    0.955668
7          Body Mass Index     0.070582    1.073133
8                Education    -0.011864    0.988206
9                 Children     0.139588    1.149800
10                    Pets    -0.070528    0.931902
11             Month Value     0.068608    1.071016
12   Excessive Absenteeism     4.653495  104.951106

In [54]:
summary_table.sort_values('Odds_Ratio',ascending = False)

Feature name  Coefficient  Odds_Ratio
12   Excessive Absenteeism     4.653495  104.951106
1                 Reason_1     0.343771    1.410255
3                 reason_3     0.233854    1.263460
5   Transportation Expense     0.197549    1.218413
9                 Children     0.139588    1.149800
7          Body Mass Index     0.070582    1.073133
11             Month Value     0.068608    1.071016
2                 reason_2     0.000624    1.000624
8                Education    -0.011864    0.988206
6                      Age    -0.045345    0.955668
10                    Pets    -0.070528    0.931902
4                 reason_4    -0.263597    0.768283
0                Intercept    -0.481896    0.617611

## testing the model

In [55]:
reg.score(x_test,y_test)

1.0

In [56]:
predicted_proba = reg.predict_proba(x_test)

In [57]:
predicted_proba

array([[0.99375109, 0.00624891],
       [0.01076552, 0.98923448],
       [0.00949158, 0.99050842],
       [0.99465261, 0.00534739],
       [0.00436867, 0.99563133],
       [0.00879016, 0.99120984],
       [0.00739479, 0.99260521],
       [0.00680067, 0.99319933],
       [0.99433833, 0.00566167],
       [0.01482829, 0.98517171],
       [0.00931979, 0.99068021],
       [0.00649047, 0.99350953],
       [0.00516724, 0.99483276],
       [0.01322951, 0.98677049],
       [0.00901672, 0.99098328],
       [0.01048432, 0.98951568],
       [0.99163585, 0.00836415],
       [0.01007175, 0.98992825],
       [0.00840609, 0.99159391],
       [0.00482441, 0.99517559],
       [0.99312165, 0.00687835],
       [0.99465261, 0.00534739],
       [0.00940133, 0.99059867],
       [0.99086308, 0.00913692],
       [0.00873565, 0.99126435],
       [0.99375939, 0.00624061],
       [0.99117626, 0.00882374],
       [0.01660534, 0.98339466],
       [0.98976474, 0.01023526],
       [0.99465261, 0.00534739],
       [0.

In [58]:
predicted_proba.shape

(126, 2)

In [59]:
predicted_proba[:,1]

array([0.00624891, 0.98923448, 0.99050842, 0.00534739, 0.99563133,
       0.99120984, 0.99260521, 0.99319933, 0.00566167, 0.98517171,
       0.99068021, 0.99350953, 0.99483276, 0.98677049, 0.99098328,
       0.98951568, 0.00836415, 0.98992825, 0.99159391, 0.99517559,
       0.00687835, 0.00534739, 0.99059867, 0.00913692, 0.99126435,
       0.00624061, 0.00882374, 0.98339466, 0.01023526, 0.00534739,
       0.98836725, 0.99201282, 0.01015843, 0.99103506, 0.00534739,
       0.99039573, 0.00577302, 0.99084891, 0.98886494, 0.99201007,
       0.0052442 , 0.98935484, 0.00600229, 0.01394538, 0.01379356,
       0.98776127, 0.99210643, 0.00624891, 0.00559542, 0.005143  ,
       0.99140054, 0.01218053, 0.99120984, 0.00628886, 0.99410624,
       0.00829353, 0.99360722, 0.985325  , 0.01130123, 0.01152221,
       0.99232914, 0.99103752, 0.0066944 , 0.0108337 , 0.98514201,
       0.00601028, 0.006854  , 0.00577302, 0.99063129, 0.98775529,
       0.00577302, 0.01097049, 0.99490693, 0.00849867, 0.99145

In [62]:
import pandas as pd

# Check target distribution properly
print("Train target distribution:\n", pd.Series(y_train).value_counts())
print("Test target distribution:\n", pd.Series(y_test).value_counts())


Train target distribution:
 0    318
1    256
Name: count, dtype: int64
Test target distribution:
 0    63
1    63
Name: count, dtype: int64


## Save the Model

In [63]:
import pickle

In [64]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [65]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)